# Site settings
title: Noddy Software
header-img: img/home-bg.jpg
email: contact@noddy.io
copyright_name: Noddy Software
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://noddy.io"
twitter_username: noddysoftware
github_username: noddysoftware
facebook_username: noddysoftware
email_username: contact@noddy.io

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-92183167-1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
