# Site settings
title: Noddy Software
header-img: img/home-bg.jpg
email: contact@noddy.io
copyright_name: Noddy Software
description: "A software development studio based in Kansas City, Missouri!"
baseurl: ""
url: "http://noddy.io"
facebook_username: noddysoftware
twitter_username: noddysoftware
youtube_username: noddysoftware
reddit_username: noddysoftware
github_username: noddysoftware
email_username: contact@noddy.io

# Google Analytics
google_tracking_id: UA-92183167-1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: "blog/page:num"
exclude: ["less", "node_modules", "Gruntfile.js", "package.json", "README.md"]

gems: [jekyll-paginate, jekyll-feed]
